"""Literal category/interval expectations, not generated by the classifier."""
import pytest
from test_v141_a_accounting import _api, _activity, _inputs, _sync
from exposedpath_v141.a_accounting import calculate_a_windows


@pytest.mark.parametrize('name', ['cuKernelGetFunction','cuKernelGetFunction_v12000',
    'cudaStreamIsCapturing','cudaStreamIsCapturing_v10000'])
def test_supported_non_submit_is_api_not_unknown(name):
    record=calculate_a_windows(_inputs(apis=(_api('q',10,30,name,5),),syncs=(),activities=()))[0]
    assert [record[k] for k in ('A_host_path_ns','A_cuda_api_non_submit_ns','A_unattributed_ns')]==[80,20,0]


@pytest.mark.parametrize('name', ['cudaMystery','cuKernelGetFunction_vx','cuKernelGetFunction_v12_extra',
    'cudaStreamSynchronize','cudaMemcpy','cudaMalloc'])
def test_unknown_or_unrecovered_sync_never_inferred_from_activity(name):
    record=calculate_a_windows(_inputs(apis=(_api('q',10,30,name,5),),syncs=(),
        activities=(_activity('k',40,50,'KERNEL',5),)))[0]
    assert record['A_unattributed_ns']==20 and record['A_cuda_api_ns']==0


def test_non_submit_activity_conflict_remains_unknown():
    record=calculate_a_windows(_inputs(apis=(_api('q',10,30,'cuKernelGetFunction',5),),syncs=(),
        activities=(_activity('k',40,50,'KERNEL',5),)))[0]
    assert record['A_unattributed_ns']==20


def test_non_submit_failure_is_not_silently_accepted_and_legacy_not_ready_is_preserved():
    failed={**_api('q',10,30,'cudaStreamIsCapturing_v10000',5),'return_value':900}
    record=calculate_a_windows(_inputs(apis=(failed,),syncs=(),activities=()))[0]
    assert record['A_unattributed_ns']==20
    query={**_api('q',10,30,'cudaStreamQuery',5),'return_value':34}
    record=calculate_a_windows(_inputs(apis=(query,),syncs=(),activities=()))[0]
    assert record['A_cuda_api_non_submit_ns']==20


@pytest.mark.parametrize('name',['cudaLaunchKernel_v7000','cuLaunchKernel','cudaMemcpyAsync_v3020','cudaMemsetAsync_v3020'])
def test_submit_rule_still_requires_observed_activity(name):
    api=_api('s',10,20,name,6)
    missing=calculate_a_windows(_inputs(apis=(api,),syncs=(),activities=()))[0]
    assert missing['A_unattributed_ns']==10
    present=calculate_a_windows(_inputs(apis=(api,),syncs=(),activities=(_activity('k',40,50,'KERNEL',6),)))[0]
    assert present['A_cuda_api_submit_ns']==10


def test_non_submit_union_and_sync_priority():
    record=calculate_a_windows(_inputs(apis=(_api('q',10,40,'cuKernelGetFunction',5),
        _api('q2',15,25,'cudaStreamIsCapturing_v10000',6)),
        syncs=(_sync('s',20,30,'VALID_EMPTY',[]),),activities=()))[0]
    assert [record[k] for k in ('A_host_path_ns','A_cuda_api_non_submit_ns','A_sync_residual_ns','A_unattributed_ns')]==[70,20,10,0]


def test_invalid_sync_and_owner_conflict_stay_unknown():
    record=calculate_a_windows(_inputs(apis=(_api('q',10,40,'cuKernelGetFunction',5),),
        syncs=(_sync('s',20,30,'INVALID',[],'MISSING_CORRELATION'),),activities=()))[0]
    assert [record[k] for k in ('A_cuda_api_non_submit_ns','A_unattributed_ns')]==[20,10]
    record=calculate_a_windows(_inputs(apis=(_api('q',10,40,'cuKernelGetFunction',5,global_tid=999),),
        syncs=(),activities=()))[0]
    assert record['A_unattributed_ns']==30 and record['A_cuda_api_ns']==0


def test_mixed_submit_non_submit_overlap_is_not_double_counted_or_guessed():
    record=calculate_a_windows(_inputs(apis=(_api('q',10,30,'cuKernelGetFunction',5),
        _api('launch',20,40,'cudaLaunchKernel_v7000',6)),syncs=(),
        activities=(_activity('k',45,50,'KERNEL',6),)))[0]
    assert [record[k] for k in ('A_host_path_ns','A_cuda_api_submit_ns','A_cuda_api_non_submit_ns','A_unattributed_ns')]==[70,10,10,10]
